imports:
    - { resource: '../../../symplify/easy-coding-standard/config/set/symfony.yaml' }
    - { resource: 'whatwedo-common.yml' }

services:
    PhpCsFixerCustomFixers\Fixer\NoDoctrineMigrationsGeneratedCommentFixer: ~

parameters:
    skip:
        Symplify\CodingStandard\Sniffs\Naming\AbstractClassNameSniff:
            - '**/Entity/*.php'
