imports:
    - { resource: '%vendor_dir%/symplify/better-phpdoc-parser/config/config.yaml' }
    - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/clean-code.yml' }
    - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/common.yml' }
    - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/psr2.yml' }
#    - { resource: '%vendor_dir%/symplify/coding-standard/config/symplify.yml' }

services:
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Classes\ValidClassNameSniff: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\ClassComment: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\FileComment: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\FunctionCommentThrowTag: ~
    PhpCsFixer\Fixer\ClassNotation\OrderedClassElementsFixer:
        order:
        - 'use_trait'
        - 'constant_public'
        - 'constant_protected'
        - 'constant_private'
        - 'property_public'
        - 'property_protected'
        - 'property_private'
        - 'construct'
        - 'destruct'
        - 'method_public'
        - 'method_protected'
        - 'method_private'
        - 'phpunit'
        - 'magic'
        - 'magic'
    PhpCsFixer\Tokenizer\Analyzer\ArgumentsAnalyzer: ~
    PhpCsFixerCustomFixers\Fixer\NoImportFromGlobalNamespaceFixer: ~
    PhpCsFixerCustomFixers\Fixer\NoNullableBooleanTypeFixer: ~
    PhpCsFixerCustomFixers\Fixer\NoPhpStormGeneratedCommentFixer: ~
    PhpCsFixerCustomFixers\Fixer\PhpdocSelfAccessorFixer: ~
    PhpCsFixerCustomFixers\Fixer\PhpdocVarAnnotationCorrectOrderFixer: ~
    SlevomatCodingStandard\Sniffs\Commenting\ForbiddenAnnotationsSniff:
        forbiddenAnnotations:
            - '@author'
            - '@created'
            - '@version'
    SlevomatCodingStandard\Sniffs\ControlStructures\AssignmentInConditionSniff: ~
    SlevomatCodingStandard\Sniffs\ControlStructures\DisallowEmptySniff: ~
    SlevomatCodingStandard\Sniffs\Exceptions\DeadCatch: ~
    SlevomatCodingStandard\Sniffs\Namespaces\ReferenceUsedNamesOnlySniff:
        searchAnnotations: true
        allowFallbackGlobalFunctions: true
        allowFallbackGlobalConstants: true
        allowPartialUses: false
    SlevomatCodingStandard\Sniffs\Namespaces\UseFromSameNamespace: ~
    SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff: ~

parameters:
    exclude_checkers:
        - PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\AssignmentInConditionSniff
        - PHP_CodeSniffer\Standards\Generic\Sniffs\ControlStructures\InlineControlStructureSniff
        - PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\ScopeIndentSniff
        - PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ScopeClosingBraceSniff
        - PhpCsFixer\Fixer\CastNotation\CastSpacesFixer
        - PhpCsFixer\Fixer\ControlStructure\NoTrailingCommaInListCallFixer
        - PhpCsFixer\Fixer\ControlStructure\YodaStyleFixer
        - PhpCsFixer\Fixer\LanguageConstruct\IsNullFixer
        - PhpCsFixer\Fixer\NamespaceNotation\BlankLineAfterNamespaceFixer
        - PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer
        - PhpCsFixer\Fixer\Operator\ConcatSpaceFixer
        - PhpCsFixer\Fixer\Operator\IncrementStyleFixer
        - PhpCsFixer\Fixer\Operator\NotOperatorWithSuccessorSpaceFixer
        - PhpCsFixer\Fixer\Operator\UnaryOperatorSpacesFixer
        - PhpCsFixer\Fixer\Phpdoc\BlankLineBeforeStatementFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocAlignFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocInlineTagFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocNoAliasTagFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocNoEmptyReturnFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocNoPackageFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocSummaryFixer
        - PhpCsFixer\Fixer\Phpdoc\PhpdocToCommentFixer
        - PhpCsFixer\Fixer\ReturnNotation\ReturnAssignmentFixer
        - PhpCsFixer\Fixer\Strict\StrictComparisonFixer
        - PhpCsFixer\Fixer\Strict\StrictParamFixer
        - PhpCsFixer\Fixer\Whitespace\BlankLineBeforeStatementFixer
        - PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer
        - PhpCsFixer\Fixer\Whitespace\NoExtraBlankLinesFixer
        - SlevomatCodingStandard\Sniffs\Classes\TraitUseSpacingSniff
        - SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff
        - SlevomatCodingStandard\Sniffs\Commenting\EmptyCommentSniff
        - SlevomatCodingStandard\Sniffs\PHP\UselessSemicolonSniff
        - SlevomatCodingStandard\Sniffs\Variables\UselessVariableSniff
        - Symplify\CodingStandard\Fixer\Commenting\RemoveUselessDocBlockFixer
        - Symplify\CodingStandard\Fixer\Naming\PropertyNameMatchingTypeFixer
        - Symplify\CodingStandard\Fixer\Solid\FinalInterfaceFixer
        - Symplify\CodingStandard\Sniffs\Architecture\ExplicitExceptionSniff
        - Symplify\CodingStandard\Sniffs\CleanCode\CognitiveComplexitySniff
        - Symplify\CodingStandard\Sniffs\CleanCode\ForbiddenReferenceSniff
        - Symplify\CodingStandard\Sniffs\CleanCode\ForbiddenStaticFunctionSniff
        - Symplify\CodingStandard\Sniffs\Commenting\VarConstantCommentSniff
        - Symplify\CodingStandard\Sniffs\ControlStructure\SprintfOverContactSniff
        - Symplify\CodingStandard\Sniffs\DeadCode\UnusedPublicMethodSniff
        - Symplify\CodingStandard\Sniffs\Debug\CommentedOutCodeSniff
        - Symplify\CodingStandard\Sniffs\DependencyInjection\NoClassInstantiationSniff

    skip:
        PHP_CodeSniffer\Standards\Squiz\Sniffs\Classes\ValidClassNameSniff:
            - '**/whatwedo*.php'
